#!/usr/bin/python3
import os
from multiprocessing import Process, current_process
import subprocess
from py3nvml.py3nvml import *
import time
import py3nvml
import datetime

nvmlInit()

def current_temp_():
    while True:
        time.sleep(1)
        handle = nvmlDeviceGetHandleByIndex(0)
        print(f"GPU", nvmlDeviceGetIndex(handle),
              f"| Temp: {nvmlDeviceGetTemperature(handle, NVML_TEMPERATURE_GPU)}",
              f"| Consump : {int(nvmlDeviceGetPowerUsage(handle) / 1000)}"
              f"| PL: {int(nvmlDeviceGetEnforcedPowerLimit(handle) / 1000)}",
              f"| Proc ID: {os.getpid()}",
              nvmlDeviceGetName(handle),
              "|",
              str(datetime.datetime.now().strftime("%Y-%m-%d ""%H:%M:%S")))


if __name__ == "__main__":
    current_temp_()
